[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -jar build/libs/hanabank-backend-0.0.1-SNAPSHOT.jar"

[env]
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
